---
- name: Install Node.js
  apt: 
    name: nodejs
    state: present
    update_cache: yes
- name: Install npm
  apt:
    name: npm
    state: present
    update_cache: yes
- name: Deploy Backend app
  copy:
    src: app.js
    dest: /var/www/html/app.js
- name: Start backend app
  shell: "nohup node /var/www/html/app.js &"
  args:
    chdir: /var/www/html