---
- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install npm
  apt:
    name: npm
    state: present

- name: Deploy backend app
  copy:
    src: app.js
    dest: /home/ubuntu/app.js

- name: Start backend app
  shell: "nohup node /home/ubuntu/app.js &"
