---
- name: Update apt repository
  apt:
    update_cache: yes
- name: Install openJDK
  apt:
    name: openjdk-11-jdk
    state: present
   
- name: Update apt repo
  apt:
    name: nginx
    state: present
- name : Start and enable Nginx
  service: 
    name: nginx
    state: started
    enabled: yes
- name: copy the index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
- name: Restart Nginx
  service:
    name: nginx
    state: restarted