- name: Launch EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no 
  vars_files:
    - vars.yml
  roles:
    - create_instance

- name: wait for EC2 instance to appear in inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause to allow EC2 Registration
      pause:
        seconds: 60

- name: Configure EC2 frontend
  hosts: launched
  roles:
    - frontend 

- name: Configure EC2 backend
  hosts: launched
  roles:
    - backend 
  