---
- name: Launch EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  roles:
    - create_instance

 
- name: Configure EC2 frontend
  hosts: launched
  remote_user: ubuntu   # use ec2-user if Amazon Linux AMI
  become: true
  roles:
    - frontend
