
#for code coverage (xml file)
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectKey=nikunj_sonar_key
#sonarcube server details
sonar.host.url= http://localhost:9000
sonar.token=sqa_4fac42dea7a84ee166deb5e534026db909e7bf1d