- name: Launch EC2 Instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    region: "{{ region }}"
    security_groups: 
      - "{{ security_group }}"
    wait: yes
    count: 1
    network:
      assign_public_ip: yes
    tags:
      Name: "{{ instance_name }}"
      Environment: dev
  register: ec2
- name: Add new instance to inventory group 
  add_host: 
    name: "{{ item.public_ip_address }}"
    groups: launched
  loop: "{{ ec2.instances }}"
  
- name: Save dynamic inventory to file
  copy:
    dest: ./inventory.yml
    content: |
      all:
        hosts:
          webserver:
            ansible_host: {{ ec2.instances[0].public_ip_address }}
            ansible_user: ubuntu
            ansible_ssh_private_key_file: ./nikunj.pem